language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
    
node_js:
  - "node"
  - "7"
  - "8"

branches:
  only:
    - gh-pages
    
# be nice and limit workload; queued commits older than this value will not be built
git:
  depth: 5

# do lint here
before_script:

script:
  - npm run build
