language: node_js
    
node_js:
  - "node"
  - "7"
  - "8"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-demjson

before_script:
  - jsonlint meta/*.json
  
script:
  - npm run build

branches:
  only:
    - gh-pages
    - /.*/

